name: Build and Deploy Sphinx

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs-requirements.txt

      - name: Build Sphinx site
        run: |
          sphinx-build -b html docs docs/_build
        env:
          LC_ALL: C.UTF-8
          LANG: C.UTF-8

      - name: Deploy to gh-pages branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cd docs/_build && \
          git init && \
          git add . && \
          git commit -m "Deployed by GitHub Action" && \
          git push --force "https://$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" master:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

